### ISSUE TITLE
Unnecessary sxmo packages

### ISSUE THREAD

**Issue by puffnfresh** [wentam/sxmo-nix#19]
Trying to build sxmo via `modules/sxmo` results in building mpv, pamixer, mako, wob, etc. Some of these are Wayland specific so shouldn't be needed for sxmo and some are media related (I'm trying to get an e-reader working) so I'm not sure why they're included.

I've directly included `sxmo.nix` directly instead for now but that probably means I'm missing out on other important things.

**Comment by wentam** [comment]
Yup, deps between swmo vs sxmo are a mess right now!

Many of these are included packages because sxmo calls these programs (for example, mpv is used to play all the 'system' sounds). Some of them should be optional, like pamixer (sxmo only calls pamixer if you're using pulse).

sxmo is basically a bunch of shell scripts that tie stuff together, so a lot of utilities need to get pulled in for the system to function.

I also need to figure out what should be pulled in from the module and what should be pulled in through the package. Focus is on getting everything working for right now, and I've just been throwing everything in the list.

Edit: I realize now you're referring at least in part to including modules/sxmo/default.nix vs modules/sxmo/sxmo.nix. That's a good point. sxmo/swmo modules should include a 'common.nix', I'm doing this backwards.

**Comment by wentam** [comment]
Please look at 4b70abab8c870afa9dc1ea426eb95948881670ef and let me know if that generally addresses your concern.
We still need mpv to play system sounds there. 
pamixer needs to be conditional still.

Edit: 75df385a71adc87241522d2a5020e28465ba0e35 
Edit 2: c1db1a6d70ac7880f98c3f0bef2ee1d49eabcde5 

(now if sound.enable==false and hardware.pulseaudio.enable==false, mpv and pamixer don't get pulled in)

**Comment by puffnfresh** [comment]
Those commits are working pretty well for me. Thank you!
